### ISSUE TITLE
Addition of Python notes

### ISSUE THREAD

**Issue by khd33j** [allanoguis/coding-notes#10]
## Issue Title
Add Python notes to this collection (if applicable)

## Description
This repo currently has notes for JS, TS and frameworks. I'd like to add notes for Python, if that's okay. This issue aims to track the completion of notes for Python.

## Tagging Reviewers
Requesting review from maintainers who can provide guidance and/or permission: @allanoguis
If this issue seems valid, kindly assign me this under Hacktoberfest label. Thanks!

**Comment by allanoguis** [comment]
Hi @khd33j Hope you are well! I have already assigned you the issue. feel free to apply your changes and send a PR if you are still intereseted. Sorry I was not able to tag you earlier.

**Comment by khd33j** [comment]
Yup okay!
