### ISSUE TITLE
Addition Of ReactJS Remaining Notes

### ISSUE THREAD

**Issue by anjali-vaish** [allanoguis/coding-notes#4]
## Issue Title
Complete ReactJS Notes as per README

## Description
The ReactJS notes in the repository are currently incomplete. The README file lists several subtopics that have not yet been covered in the notes. This issue aims to track the completion of these missing sections.

## Screenshots
![image](https://github.com/user-attachments/assets/53422938-ab58-4a0a-8858-6fcc87870aa3)

## Tagging Reviewers
Requesting review from maintainers who can provide guidance and/or permission: @allanoguis

**Comment by anjali-vaish** [comment]
@allanoguis Request you to assign this task to me under the hacktoberfest label. Thanks!

**Comment by allanoguis** [comment]
you can start @anjali-vaish i will assign now

**Comment by anjali-vaish** [comment]
Thanks, I'll proceed and shortly update.
