### ISSUE TITLE
Addition of AngularJS Notes

### ISSUE THREAD

**Issue by anjali-vaish** [allanoguis/coding-notes#5]
## Feature Request Title
Adding AngularJS notes to the collection.

## Description
The AngularJS notes in the repository are currently not available. This issue aims to track the completion of notes for Angularjs.

## Tagging Reviewers
Requesting review from maintainers who can provide guidance and/or permission: @allanoguis 
If this issue seems valid, kindly assign me this under **Hacktoberfest label**. Thanks!

**Comment by allanoguis** [comment]
go ahead please. @anjali-vaish  follow the markdown format and the table of contents. or if you have a better way let i eill personally approve pr

**Comment by anjali-vaish** [comment]
On it!

**Comment by allanoguis** [comment]
dont forget to leave a star if you haven't yet. thanks!
