### ISSUE TITLE
Addition to Node.js 

### ISSUE THREAD

**Issue by Satyasn01** [allanoguis/coding-notes#6]
Issue Title

Complete Node.js Notes as per README

Description

The Node.js notes in the repository are currently incomplete. The README file lists several subtopics that have not yet been covered in the notes. This issue aims to track the completion of these missing sections.

Tagging Reviewers

Requesting review from maintainers who can provide guidance and/or permission: @allanoguis

**Comment by allanoguis** [comment]
go ahead please @Satyasn01 follow the format or if you have better format please let us know. thanks

**Comment by Satyasn01** [comment]
Sure kindly assign and add the hacktoberfest/hacktoberfest-accepted label to this

**Comment by allanoguis** [comment]
doing it now dont forget to leave a star if you haven't yet. thanks!
