### ISSUE TITLE
Edit the README.md file

### ISSUE THREAD

**Issue by khd33j** [allanoguis/coding-notes#9]
## Issue Title
Edit the README.md file

## Description
- The README.md file requires some editing. The main heading and description. 
- The JS notes are currently in alphabetical order. They should instead be in order of difficulty (basics to advanced). 
This is my first time contributing to open source, hence why I found an easy issue. 😅

## Screenshots
<img width="557" alt="title" src="https://github.com/user-attachments/assets/52713e15-ad63-4547-9d1e-7f66a075e210">
<img width="253" alt="js notes structure" src="https://github.com/user-attachments/assets/50dbebcd-6a77-41b2-b1eb-c8cc50ca8417">

## Tagging Reviewers
Requesting review from maintainers who can provide guidance and/or permission: @allanoguis

**Comment by allanoguis** [comment]
go ahead @khd33j

**Comment by allanoguis** [comment]
don't forget to leave a star and if you have projects I can work on please join our discord
https://discord.gg/3Y4HsvxX
